### ISSUE TITLE
virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by Redshoee** [HSAFoundation/gccbrig#19]
When I try to make the gccbrig 
it shows the message about memory,

virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory

 and I type "top" to check
GiB Mem:     3.247 total,    3.165 used,    0.081 free,    0.005 buffe
GiB Swap:    7.629 total,    7.571 used,    0.058 free.    0.044 cache

Does it really need a big memory when I compiler it ?　
or is there  something wrong  about my configuration ?

**Comment by pjaaskel** [comment]
Something wrong with your config. Nothing special in gccbrig wrt its compilation complexity.
