### ISSUE TITLE
Wrong emission of SBR insn

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/gccbrig#3]
Running following snippet: http://pastebin.com/X2tkqnFN

Produces following BRIG with GCC HSA BE:
prog function &foo(arg_s32 %res)(
	arg_s32 %a,
	arg_s32 %b)
{
	ld_arg_align(4)_s32	$s0, [%a];

@BB_2362_2:
	sub_s32	$s0, $s0, 1;
	cvt_u64_s32	$d0, $s0;
	sbr_u64	$d0 [@BB_2362_3, @BB_2362_3, @BB_2362_4, @BB_2362_4, @BB_2362_5, @BB_2362_5, @BB_2362_6, @BB_2362_6, @BB_2362_6, @BB_2362_6, @BB_2362_6];
	br	@BB_2362_7;

@BB_2362_3:
	mov_s32	$s1, 1;
	mov_s32	$s0, $s1;
	br	@BB_2362_8;

@BB_2362_4:
	mov_s32	$s1, 2;
	mov_s32	$s0, $s1;
	br	@BB_2362_8;

@BB_2362_5:
	mov_s32	$s1, 3;
	mov_s32	$s0, $s1;
	br	@BB_2362_8;

@BB_2362_6:
	mov_s32	$s0, 4;
	mov_s32	$s0, $s0;
	br	@BB_2362_8;

@BB_2362_7:
	mov_s32	$s1, -1;
	mov_s32	$s0, $s1;

@BB_2362_8:
	st_arg_align(4)_s32	$s0, [%res];
	ret;
};

Where expected output for a == 0 is -1.

However running gccbrig produces:
http://pastebin.com/u3MBXQSD

Where $ ./a.out | HEAD:
./a.out  | head
foo: 0 = 1
foo: 1 = 1
foo: 2 = 1
foo: 3 = 2
foo: 4 = 2
foo: 5 = 3
foo: 6 = 3
foo: 7 = 4
foo: 8 = 4
foo: 9 = 4

Thanks,
Martin

**Comment by pjaaskel** [comment]
If a == 0, $d0 becomes -1 thus a larger unsigned value than there are list of targets. It makes this case undefined per specs. Your code assumes fall through from sbr in case of an out of bounds index, which probably happens to be the case with your previous implementation.

http://www.hsafoundation.com/html/HSA_Library.htm#PRM/Topics/08_Branch/branch.htm?Highlight=sbr
> The program execution is undefined if the number of labels in labelList is less than or equal to the index value.

**Comment by marxin** [comment]
Thanks for investigation, I've created issue:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70402
