### ISSUE TITLE
Website offline???

### ISSUE THREAD

**Issue by austinksmith** [HSAFoundation/gccbrig#33]
Hello, I noticed the hsafoundation site data base connection is failing. Is HSAFoundation still a real effort taking place?

http://www.hsafoundation.com/

![screenshot from 2018-03-29 17-11-04](https://user-images.githubusercontent.com/2227747/38113840-2f872ede-3374-11e8-93c4-7f21ff265074.png)

**Comment by pjaaskel** [comment]
This is not an HSA web site issue tracker.

**Comment by austinksmith** [comment]
Oh, well next time a simple thank you would be more appropriate. No need to be a douche, its not like there was anywhere else to alert you all to your website being down which has been the case going on for almost a week now.

**Comment by pjaaskel** [comment]
Ok, that came out a bit too Finnish, it seems. Sorry, and good that the web page is back up, it seems.
