### ISSUE TITLE
Wrong emission of st_align(4)_u8 HSAIL insn

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/gccbrig#4]
Running following snippet with GCC HSA BE:
http://pastebin.com/x93CvJDM

Produces:
prog kernel &main__omp_fn_0(kernarg_u64 %_omp_data_i)
{
	ld_kernarg_align(8)_u64	$d0, [%_omp_data_i];

@BB_3045_2:
	ld_align(8)_u64	$d0, [$d0];
	st_align(4)_u8	9, 0, 0, 0, [$d0+8];
	ret;
};

While running gccbrig I see following wrong store of zero value (instead of 9):
__wi_loop_x:
  d0_28 = MEM[(unsigned long *)__args_27(D)];
  _29 = VIEW_CONVERT_EXPR<unsigned char *>(d0_28);
  d0_30 = MEM[(unsigned long *)_29];
  _31 = d0_30 + 8;
  _32 = VIEW_CONVERT_EXPR<unsigned char *>(_31);
  *_32 = 0;
  __local_x_34 = __local_x_1 + 1;
  if (__cur_wg_size_x_11 > __local_x_34)
    goto <bb 5> (__wi_loop_x);
  else
    goto <bb 6>;

Thanks,
Martin

**Comment by pjaaskel** [comment]
This is an illegal instruction:

st_align(4)_u8 9, **0, 0, 0,** [$d0+8];

st takes only two arguments, this has somehow pushed in 5. HSAILasm can disassemble the BRIG, but cannot assemble it again:

```
$ HSAILasm -disassemble phsa-temp/program-0.brig 
$ HSAILasm phsa-temp/program-0.hsail

>       st_align(4)_u8  9, 0, 0, 0, [$d0+8];
>                          ^
input(10,20): Invalid operand 1, expected: an address

```

I wonder how can it work for some other platform. Using the standard struct parsing, I cannot get access to the 9 byte in that list. I'll report this to HSAILtools.

**Comment by marxin** [comment]
Ok, I will fix that in HSA back-end, however can you please paste here a link to an issue you did for HSAILAsm?

Thanks

**Comment by pjaaskel** [comment]
I didn't because I wasn't sure if this is a HSAILasm bug after all. It should complain in case trying to disassemble an illegal BRIG such as this? It complains when it tries to assembly it.

**Comment by marxin** [comment]
I think so, because they do it in different situations where an assembled BRIG is invalid.
They will appreciate that, maybe it can catch more cases.

Martin
