### ISSUE TITLE
alloca insn in not supported

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/gccbrig#5]
Having a test-case with:
	alloca_align(8)_u32	$s1, $s1;

Produces ICE in:
In function ‘_main__omp_fn_0’:
brig1: internal compiler error: mem inst opcode 104 not implemented
0x590318 brig_mem_inst_handler::build_mem_access(BrigInstBase const*, tree_node*, tree_node*)
	../../gcc/brig/brigfrontend/brig-mem-inst-handler.cc:40
0x5903aa brig_mem_inst_handler::operator()(BrigBase const*)
	../../gcc/brig/brigfrontend/brig-mem-inst-handler.cc:155
0x593fec brig_to_generic::write_globals()
	../../gcc/brig/brigfrontend/brig_to_generic.cc:625
0x581a9d brig_langhook_write_globals
	../../gcc/brig/brig-lang.c:349

Thanks,
Martin

**Comment by pjaaskel** [comment]
Alloca implemented in 09d873adb9b7a1a061301291 please reopen if you find a bug with it.

**Comment by marxin** [comment]
My internal test works with fixed gccbrig.
Thanks
