### ISSUE TITLE
Emission of a function with array type as arguments produces ICE

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/gccbrig#6]
Running GCC HSA BE of:
http://pastebin.com/v6DVryXw

HSAIL:
prog function &foo(align(4) arg_u8 %res[12])(align(4) arg_u8 %c[12])
{
	align(4) private_u8 %__private_0[12];
	align(4) private_u8 %__hsa_anonymous_2357[12];
	ld_arg_align(8)_u64	$d0, [%c];
	st_private_align(8)_u64	$d0, [%__private_0];
	ld_arg_align(4)_u32	$s0, [%c][8];
	st_private_align(4)_u32	$s0, [%__private_0][8];

@BB_2354_2:
	st_private_align(4)_s32	11, [%__private_0];
	ld_private_align(8)_u64	$d0, [%__private_0];
	st_private_align(8)_u64	$d0, [%__hsa_anonymous_2357];
	ld_private_align(4)_u32	$s0, [%__private_0][8];
	st_private_align(4)_u32	$s0, [%__hsa_anonymous_2357][8];

@BB_2354_3:
	ld_private_align(8)_u64	$d0, [%__hsa_anonymous_2357];
	st_arg_align(8)_u64	$d0, [%res];
	ld_private_align(4)_u32	$s0, [%__hsa_anonymous_2357][8];
	st_arg_align(4)_u32	$s0, [%res][8];
	ret;
};

Produces following ICE:
http://pastebin.com/WdJYZ9Ne

Thanks,
Martin

**Comment by pjaaskel** [comment]
I fixed the gccbrig issue that caused the ICE, but you might want to check your output also.
There's possibly also an alignment issue here:

prog function &foo(align(4) arg_u8 %res[12])(**align(4)** arg_u8 %c[12])
{
align(4) private_u8 %__private_0[12];
align(4) private_u8 %__hsa_anonymous_2357[12];
ld_arg_**align(8)**_u64 $d0, [%c];
....

**Comment by marxin** [comment]
This is definitely a problem, I will investigate that.

Thanks,
Martin
