### ISSUE TITLE
Undefined symbol for 'decl prog align(4) global_s8 &CSWTCH_12[44]' global variable

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/gccbrig#8]
Hello.

Compiling http://pastebin.com/00S64WAs:
$ gcc -O2 -g -fdump-tree-hsagen -fno-tree-vectorize -fopenmp switch-3.c
$ ./a.out
dlopen() error: /tmp/phsa-finalizer-4gw71X/ec73e258e6d9.so: undefined symbol: CSWTCH_12
symbol 'main__omp_fn_0' got address 0!
Aborted (core dumped)

Thanks,
Martin

**Comment by pjaaskel** [comment]
Implemented host-defined program variables which fixed this.
